spring:
  application:
    name: central-module
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:thermo-tasker}
    username: ${CENTRAL_DB_USER:central_module_user}
    password: ${CENTRAL_DB_PASS:central_module_user_pass}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

message-broker:
  dead-letter:
    exchange:
      name: ${DEAD_LETTER_EXCHANGE_NAME:dlx.exchange}
    queue:
      name: ${DEAD_LETTER_QUEUE_NAME:dlq.queue}
      routing-key: ${DEAD_LETTER_ROUTING_KEY:dlq.routingKey}
  tasks-queue:
    name: ${TASKS_QUEUE_NAME:tasks.queue}
