spring:
  application:
    name: central-module
  datasource:
    url: jdbc:postgresql://localhost:5432/thermo-tasker
    username: central_module_user
    password: central_module_user_pass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

message-broker:
  dead-letter:
    exchange:
      name: dlx.exchange
    queue:
      name: dlq.queue
      routing-key: dlq.routingKey
  tasks-queue:
    name: tasks.queue
