spring:
  application:
    name: central-module
  datasource:
    url: jdbc:h2:mem:thermo-tasker
    username: dev
    password: dev
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

message-broker:
  dead-letter:
    exchange:
      name: dlx.exchange
    queue:
      name: dlq.queue
      routing-key: dlq.routingKey
  tasks-queue:
    name: tasks.queue

sql:
  init:
    platform: h2
