name: Docker Publish Release

on:
  release:
    types: [released]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push central-module
        run: |
          cd central-module
          docker build -t ghcr.io/${{ github.repository_owner }}/thermo-tasker/central-module:latest .
          docker push ghcr.io/${{ github.repository_owner }}/thermo-tasker/central-module:latest

      - name: Build and push printer-module
        run: |
          cd printer-module
          docker build -t ghcr.io/${{ github.repository_owner }}/thermo-tasker/printer-module:latest .
          docker push ghcr.io/${{ github.repository_owner }}/thermo-tasker/printer-module:latest
